import { InfoPage, InfoSection } from "@/components/info-page";
export default function Returns(){return <InfoPage eyebrow="MÜŞTERİ HİZMETLERİ" title="İptal ve iade politikası." intro="Cayma, iptal, değişim ve ayıplı ürün süreçlerinde haklarınızı ve izlemeniz gereken adımları açıklıyoruz.">
  <InfoSection title="Sipariş iptali"><p>Kargoya verilmemiş siparişler için en kısa sürede müşteri hizmetlerine ulaşın. Hazırlık durumuna göre iptal gerçekleştirilir. Kargoya verilen siparişlerde cayma ve iade süreci uygulanır.</p></InfoSection>
  <InfoSection title="14 günlük cayma hakkı"><p>Tüketici, ürünü teslim aldığı tarihten itibaren 14 gün içinde gerekçe göstermeden cayma hakkını kullanabilir. Süre içinde <a href="mailto:info@arvoculture.com">info@arvoculture.com</a> adresine sipariş numarası ve açık cayma bildirimi göndermeniz yeterlidir.</p></InfoSection>
  <InfoSection title="ArvoCulture 30 gün kolay iade"><p>Kanuni haklarınıza ek olarak, yeniden satılabilir durumda, kullanılmamış, yıkanmamış, etiketi ve orijinal ambalajı korunmuş standart ürünler teslimden itibaren 30 gün içinde gönüllü iade politikamız kapsamında değerlendirilebilir. Bu ek imkân, ayıplı mala ilişkin kanuni haklarınızı sınırlamaz.</p></InfoSection>
  <InfoSection title="İade yöntemi ve ücret"><p>Cayma bildiriminizden sonra paylaşılacak iade talimatını izleyin. İade kargo bedelinden kimin sorumlu olduğu, sipariş öncesi bilgilendirmede ve iade talimatında belirtilir. Yanlış, eksik veya ayıplı gönderilerde kanuni sorumluluk satıcıya aittir.</p></InfoSection>
  <InfoSection title="İstisnalar"><p>Kişiye özel üretilen veya değiştirilen ürünler; çabuk bozulabilen ürünler; tesliminden sonra ambalaj, bant, mühür veya paketi açılmış ve sağlık/hijyen açısından iadesi uygun olmayan ürünler ile mevzuatta sayılan diğer hâllerde cayma hakkı kullanılamaz. İstisna, ürün sayfasında ve sipariş öncesinde ayrıca belirtilir.</p></InfoSection>
  <InfoSection title="Geri ödeme"><p>Cayma bildiriminin ulaşmasından sonra, ürünün iade edildiğine ilişkin kanıtın sunulması veya ürünün ulaşması şartlarına tabi olarak geri ödeme mevzuattaki süre içinde, satın alırken kullanılan ödeme aracına uygun biçimde yapılır. Bankanın hesaba yansıtma süresi ayrıca değişebilir.</p></InfoSection>
</InfoPage>}
