import { InfoPage, InfoSection } from "@/components/info-page";

export default function KvkkPage() {
  return <InfoPage eyebrow="KİŞİSEL VERİLER" title="KVKK aydınlatma metni." intro="Kişisel verilerinizin kim tarafından, hangi amaçlarla ve hukuki sebeplerle işlendiğini; kimlere aktarılabileceğini ve haklarınızı açıklıyoruz.">
    <InfoSection title="Veri sorumlusu"><div className="legal-card"><p><b>ARVOCULTURE GROUP TEKNOLOJİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ</b></p><p>Yakuplu Mah. Hürriyet Bulvarı Skyport Residence No:1 D:113 Beylikdüzü / İstanbul</p><p>VKN: 0861785335 · Ticaret Sicil No: 1149259</p><p><a href="mailto:info@arvoculture.com">info@arvoculture.com</a> · +90 507 437 05 07</p></div></InfoSection>
    <InfoSection title="İşlenen veri kategorileri"><ul><li>Kimlik, iletişim, fatura ve teslimat bilgileri</li><li>Sipariş, ürün, iade, ödeme durumu ve müşteri işlem kayıtları</li><li>Talep, şikâyet ve müşteri hizmetleri yazışmaları</li><li>IP adresi, oturum, cihaz, işlem güvenliği ve çerez kayıtları</li><li>İzin verilmesi hâlinde pazarlama ve iletişim tercihleri</li></ul></InfoSection>
    <InfoSection title="Amaçlar ve hukuki sebepler"><p>Veriler; üyelik ve satış sözleşmesinin kurulması ve ifası, siparişin hazırlanması, ödeme ve teslimatın yürütülmesi, iade ve destek taleplerinin sonuçlandırılması, muhasebe ve mevzuat yükümlülüklerinin yerine getirilmesi, dolandırıcılığın önlenmesi ve bilgi güvenliğinin sağlanması amaçlarıyla işlenir.</p><p>İşleme; KVKK’nın 5. maddesindeki sözleşmenin kurulması veya ifası, kanuni yükümlülük, bir hakkın tesisi/kullanılması/korunması ve temel haklara zarar vermemek kaydıyla meşru menfaat sebeplerine dayanır. Yalnızca tercihe bağlı pazarlama ve zorunlu olmayan çerezler bakımından gerektiğinde açık rıza alınır.</p></InfoSection>
    <InfoSection title="Aktarım"><p>Veriler, amaçla sınırlı ve gerekli olduğu ölçüde kargo ve lojistik firmalarına, bankalara ve yetkili ödeme kuruluşlarına, e-fatura/muhasebe hizmetlerine, barındırma ve bilgi teknolojisi tedarikçilerine, mesleki danışmanlara ve kanunen yetkili kamu kurumlarına aktarılabilir. Yurt dışı altyapı sağlayıcısı kullanılması hâlinde KVKK’nın 9. maddesindeki şartlar ve uygun güvenceler uygulanır.</p></InfoSection>
    <InfoSection title="Toplama ve saklama"><p>Veriler; web sitesi formları, sipariş ve ödeme akışları, e-posta, telefon, çerezler ve müşteri destek kanalları üzerinden otomatik veya kısmen otomatik yollarla elde edilir. Yalnızca ilgili mevzuatta öngörülen veya işleme amacı için gereken süre boyunca saklanır; süre sonunda silinir, yok edilir veya anonimleştirilir.</p></InfoSection>
    <InfoSection title="KVKK madde 11 haklarınız"><p>Verilerinizin işlenip işlenmediğini öğrenme; işlenmişse bilgi isteme; amacına uygun kullanımı öğrenme; aktarılan kişileri bilme; eksik veya yanlış veriyi düzelttirme; şartları oluştuğunda silme/yok etme; bu işlemlerin alıcılara bildirilmesini isteme; otomatik analiz sonucuna itiraz etme ve kanuna aykırı işleme nedeniyle zararın giderilmesini talep etme haklarına sahipsiniz.</p></InfoSection>
    <InfoSection title="Başvuru"><p>Kimliğinizi doğrulamaya yeterli bilgi ve talebinizin açıklamasıyla <a href="mailto:info@arvoculture.com">info@arvoculture.com</a> adresine veya veri sorumlusu adresine başvurabilirsiniz. Başvurular, mevzuattaki usul ve sürelerde sonuçlandırılır.</p><p className="legal-note">Son güncelleme: 30 Ağustos 2026.</p></InfoSection>
  </InfoPage>;
}
