import { InfoPage, InfoSection } from "@/components/info-page";
export default function DistanceSales(){return <InfoPage eyebrow="SÖZLEŞMELER" title="Mesafeli satış sözleşmesi." intro="Bu metin, ödeme adımında alıcı ve sipariş bilgileriyle tamamlanarak kurulan mesafeli satış sözleşmesinin esaslarını içerir.">
  <InfoSection title="1. Taraflar"><div className="legal-card"><p><b>Satıcı:</b> ARVOCULTURE GROUP TEKNOLOJİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ</p><p><b>Adres:</b> Yakuplu Mah. Hürriyet Bulvarı Skyport Residence No:1 D:113 Beylikdüzü / İstanbul</p><p><b>VKN / Sicil:</b> 0861785335 / 1149259</p><p><b>E-posta / Telefon:</b> info@arvoculture.com / +90 507 437 05 07</p></div><p>Alıcının adı, adresi, telefonu ve e-posta adresi sipariş ekranında beyan ettiği bilgilerdir.</p></InfoSection>
  <InfoSection title="2. Siparişe özel bilgiler"><div className="legal-fields"><div className="legal-field"><b>Sipariş numarası</b>Ödeme adımında oluşturulur</div><div className="legal-field"><b>Sözleşme tarihi</b>Sipariş onay tarihi</div><div className="legal-field"><b>Ürün ve adet</b>Sipariş özetinde gösterilir</div><div className="legal-field"><b>Toplam bedel</b>Vergi, indirim ve kargo dâhil gösterilir</div><div className="legal-field"><b>Ödeme yöntemi</b>Alıcının seçtiği yöntem</div><div className="legal-field"><b>Teslimat</b>Seçilen adres ve tahmini süre</div></div></InfoSection>
  <InfoSection title="3. Konu ve sözleşmenin kurulması"><p>Sözleşmenin konusu, alıcının elektronik ortamda özelliklerini ve satış fiyatını gördüğü ürünlerin satışı ve teslimidir. Alıcı, siparişi ödeme yükümlülüğü doğurduğu açıkça belirtilen onayla tamamladığında sözleşme kurulur. Ön bilgilendirme formu sözleşmenin ayrılmaz parçasıdır.</p></InfoSection>
  <InfoSection title="4. Fiyat ve ödeme"><p>Ürün bedeli, vergiler, indirimler, kargo ve varsa diğer masraflar sipariş özetinde gösterilir. Ödeme, seçilen yöntemle gerçekleştirilir. Kart bilgileri yetkili ödeme hizmeti sağlayıcısının güvenli altyapısında işlenir.</p></InfoSection>
  <InfoSection title="5. Teslimat"><p>Satıcı, siparişi belirtilen tahmini sürede ve mevzuattaki azami süreyi aşmadan alıcıya veya gösterdiği kişiye teslim eder. İfanın imkânsızlaşması hâlinde alıcı bilgilendirilir ve tahsil edilen bedeller mevzuattaki süre içinde iade edilir.</p></InfoSection>
  <InfoSection title="6. Cayma hakkı"><p>Alıcı, malı teslim aldığı tarihten itibaren 14 gün içinde gerekçe göstermeden cayabilir. Bildirim info@arvoculture.com adresine veya kalıcı veri saklayıcısıyla yapılabilir. Ürün, bildirimden sonra mevzuattaki süre içinde, talimatta belirtilen yöntemle geri gönderilir.</p></InfoSection>
  <InfoSection title="7. Cayma istisnaları"><p>Kişiye özel hazırlanan ürünler, çabuk bozulabilen mallar, fiyatı finansal piyasa dalgalanmalarına bağlı ürünler, teslimden sonra koruyucu ambalajı açılan ve hijyen açısından iadesi uygun olmayan ürünler ile yönetmelikte sayılan diğer sözleşmeler cayma hakkı dışındadır.</p></InfoSection>
  <InfoSection title="8. Ayıplı mal ve şikâyet"><p>Alıcının ayıplı mala ilişkin onarım, değişim, bedel indirimi veya sözleşmeden dönme dâhil kanuni seçimlik hakları saklıdır. Talepler info@arvoculture.com üzerinden iletilebilir.</p></InfoSection>
  <InfoSection title="9. Uyuşmazlık"><p>Alıcı, her takvim yılı için ilan edilen parasal sınırlar dâhilinde tüketici hakem heyetine; diğer hâllerde tüketici mahkemesine başvurabilir. Zorunlu tüketici mevzuatı hükümleri saklıdır.</p></InfoSection>
</InfoPage>}
