import { InfoPage, InfoSection } from "@/components/info-page";
export default function PreInfo(){return <InfoPage eyebrow="SİPARİŞ ÖNCESİ" title="Ön bilgilendirme formu." intro="Siparişinizi onaylamadan önce satıcıyı, ürünü, toplam bedeli, teslimatı ve cayma koşullarını kontrol etmenizi sağlayan bilgilendirme metni.">
  <InfoSection title="Satıcı"><div className="legal-card"><p><b>ARVOCULTURE GROUP TEKNOLOJİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ</b></p><p>Yakuplu Mah. Hürriyet Bulvarı Skyport Residence No:1 D:113 Beylikdüzü / İstanbul</p><p>info@arvoculture.com · +90 507 437 05 07</p><p>VKN 0861785335 · Ticaret Sicil No 1149259</p></div></InfoSection>
  <InfoSection title="Sipariş özeti"><p>Ürünün temel nitelikleri, rengi/bedeni veya varyantı, adedi, birim fiyatı, indirimler, vergiler, kargo bedeli ve ödenecek toplam tutar ödeme öncesi sipariş özetinde gösterilir. Alıcı bu bilgileri kontrol ederek siparişi onaylar.</p></InfoSection>
  <InfoSection title="Ödeme"><p>Kullanılabilir ödeme yöntemleri ödeme ekranında gösterilir. Ödeme yöntemi kaynaklı ücret veya taksit farkı varsa onaydan önce toplam bedele dâhil edilir. Kart verileri yetkili ödeme kuruluşu tarafından işlenir.</p></InfoSection>
  <InfoSection title="Teslimat"><p>Teslimat adresi, kargo yöntemi ve tahmini süre sipariş özetinde yer alır. Sipariş, taahhüt edilen sürede ve her hâlükârda yasal azami süre içinde teslim edilir. Teslimat kısıtı bulunan bölgeler onaydan önce belirtilir.</p></InfoSection>
  <InfoSection title="Cayma ve iade"><p>Mal tesliminden itibaren 14 gün içinde info@arvoculture.com adresine açık bildirim göndererek cayabilirsiniz. İade yöntemi ve kargo sorumluluğu bildirim sonrasında iletilir. Kişiye özel ürünler ve ambalajı açılmış hijyen ürünleri gibi yasal istisnalar ürün özelinde ayrıca belirtilir.</p></InfoSection>
  <InfoSection title="Şikâyet ve başvuru"><p>Sipariş ve ürün talepleri için info@arvoculture.com veya +90 507 437 05 07 üzerinden ulaşabilirsiniz. Uyuşmazlıklarda parasal sınıra göre tüketici hakem heyetleri ve tüketici mahkemeleri yetkilidir.</p><p className="legal-note">Sipariş sırasında gösterilen ürün, fiyat, teslimat ve alıcı bilgileri bu formun ayrılmaz parçasıdır. Form, sipariş verilmeden önce elektronik ortamda onaylanır ve erişilebilir biçimde saklanır.</p></InfoSection>
</InfoPage>}
